/*

 BACKGROUNDDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __backgroundData_h_INCLUDE
#define __backgroundData_h_INCLUDE

/* Bank of tiles. */
#define backgroundDataBank 0

/* Super Gameboy palette 0 */
#define backgroundDataSGBPal0c0 6076
#define backgroundDataSGBPal0c1 8935
#define backgroundDataSGBPal0c2 6596
#define backgroundDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define backgroundDataSGBPal1c0 6076
#define backgroundDataSGBPal1c1 8935
#define backgroundDataSGBPal1c2 6596
#define backgroundDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define backgroundDataSGBPal2c0 6076
#define backgroundDataSGBPal2c1 8935
#define backgroundDataSGBPal2c2 6596
#define backgroundDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define backgroundDataSGBPal3c0 6076
#define backgroundDataSGBPal3c1 8935
#define backgroundDataSGBPal3c2 6596
#define backgroundDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define backgroundDataCGBPal0c0 32767
#define backgroundDataCGBPal0c1 31702
#define backgroundDataCGBPal0c2 32074
#define backgroundDataCGBPal0c3 26634

/* Gameboy Color palette 1 */
#define backgroundDataCGBPal1c0 32767
#define backgroundDataCGBPal1c1 0
#define backgroundDataCGBPal1c2 0
#define backgroundDataCGBPal1c3 0

/* Gameboy Color palette 2 */
#define backgroundDataCGBPal2c0 31710
#define backgroundDataCGBPal2c1 0
#define backgroundDataCGBPal2c2 0
#define backgroundDataCGBPal2c3 0

/* Gameboy Color palette 3 */
#define backgroundDataCGBPal3c0 32767
#define backgroundDataCGBPal3c1 0
#define backgroundDataCGBPal3c2 0
#define backgroundDataCGBPal3c3 0

/* Gameboy Color palette 4 */
#define backgroundDataCGBPal4c0 6076
#define backgroundDataCGBPal4c1 8935
#define backgroundDataCGBPal4c2 6596
#define backgroundDataCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define backgroundDataCGBPal5c0 6076
#define backgroundDataCGBPal5c1 8935
#define backgroundDataCGBPal5c2 6596
#define backgroundDataCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define backgroundDataCGBPal6c0 6076
#define backgroundDataCGBPal6c1 8935
#define backgroundDataCGBPal6c2 6596
#define backgroundDataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define backgroundDataCGBPal7c0 6076
#define backgroundDataCGBPal7c1 8935
#define backgroundDataCGBPal7c2 6596
#define backgroundDataCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char backgroundDataCGB[];
/* Start of tile array. */
extern const unsigned char backgroundData[];

#endif

/* End of BACKGROUNDDATA.H */
