/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : backgrounddata.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BackgroundMap_h_INCLUDE
#define __BackgroundMap_h_INCLUDE

#define BackgroundMapWidth 20
#define BackgroundMapHeight 32
#define BackgroundMapBank 0

#define BackgroundMap BackgroundMapPLN0
extern const unsigned char BackgroundMapPLN0[];
extern const unsigned char BackgroundMapPLN1[];

#endif

/* End of BACKGROUNDMAP.H */
