/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : backgrounddata.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __backgroundMap_h_INCLUDE
#define __backgroundMap_h_INCLUDE

#define backgroundMapWidth 20
#define backgroundMapHeight 32
#define backgroundMapBank 0

#define backgroundMap backgroundMapPLN0
extern const unsigned char backgroundMapPLN0[];
extern const unsigned char backgroundMapPLN1[];

#endif

/* End of BACKGROUNDMAP.H */
