/*

 BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : Z:\Users\anon\Desktop\dev\touhou\gbr\sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bg_h_INCLUDE
#define __bg_h_INCLUDE

#define bgTilemapWidth 20
#define bgTilemapHeight 32
#define bgTilemapBank 0

extern const unsigned char bgTilemap[];

#endif

/* End of BG.H */
