/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 24

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __sprites_h_INCLUDE
#define __sprites_h_INCLUDE

/* Bank of tiles. */
#define spritesBank 0

/* Super Gameboy palette 0 */
#define spritesSGBPal0c0 6076
#define spritesSGBPal0c1 8935
#define spritesSGBPal0c2 6596
#define spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define spritesSGBPal1c0 6076
#define spritesSGBPal1c1 8935
#define spritesSGBPal1c2 6596
#define spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define spritesSGBPal2c0 6076
#define spritesSGBPal2c1 8935
#define spritesSGBPal2c2 6596
#define spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define spritesSGBPal3c0 6076
#define spritesSGBPal3c1 8935
#define spritesSGBPal3c2 6596
#define spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define spritesCGBPal0c0 32767
#define spritesCGBPal0c1 19438
#define spritesCGBPal0c2 10570
#define spritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spritesCGBPal1c0 32767
#define spritesCGBPal1c1 4093
#define spritesCGBPal1c2 3223
#define spritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define spritesCGBPal2c0 32766
#define spritesCGBPal2c1 8220
#define spritesCGBPal2c2 6166
#define spritesCGBPal2c3 3114

/* Gameboy Color palette 3 */
#define spritesCGBPal3c0 32766
#define spritesCGBPal3c1 32074
#define spritesCGBPal3c2 10570
#define spritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define spritesCGBPal4c0 32766
#define spritesCGBPal4c1 13347
#define spritesCGBPal4c2 7203
#define spritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define spritesCGBPal5c0 32766
#define spritesCGBPal5c1 3073
#define spritesCGBPal5c2 13352
#define spritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define spritesCGBPal6c0 32766
#define spritesCGBPal6c1 3108
#define spritesCGBPal6c2 10282
#define spritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define spritesCGBPal7c0 32766
#define spritesCGBPal7c1 9259
#define spritesCGBPal7c2 8234
#define spritesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char spritesCGB[];
/* Start of tile array. */
extern const unsigned char sprites[];

#endif

/* End of SPRITES.H */
